=== LauraRubioG/XSD_LenguajeDeMarca/AF2.5_EjerciciosVariosDeXSD_LauraRubioGallardo/Ejercicio24_Prueba.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="aeropuerto">
        <xs:complexType>
            <xs:all>
               <xs:element name="nombre" type="xs:string"/>
               <xs:element name="vuelos">
                   <xs:complexType>
                       <xs:sequence>
                           <xs:element name="vuelo" maxOccurs="unbounded">
                               <xs:complexType>
                                   <xs:sequence>
                                       <xs:element name="diario" minOccurs="0"/>
                                       <xs:element name="origen" type="xs:string"/>
                                       <xs:element name ="destino" type="xs:string"/>
                                       <xs:element name="hora-salida" type="xs:time"/>
                                       <xs:element name="hora-llegada" type="xs:time"></xs:element>
                                   </xs:sequence>
                                   <xs:attribute name="código" type="xs:ID" use="required"/>
                                   <xs:attribute name="estado" default="E">
                                       <xs:simpleType>
                                           <xs:restriction base="xs:string">
                                               <xs:pattern value="[CER]"></xs:pattern>
                                           </xs:restriction>
                                       </xs:simpleType>
                                   </xs:attribute>
                               </xs:complexType>
                           </xs:element>
                       </xs:sequence>
                   </xs:complexType>
               </xs:element>
                <xs:element name="fecha" type="xs:date"></xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== LauraRubioG/XSD_LenguajeDeMarca/AF2.5_EjerciciosVariosDeXSD_LauraRubioGallardo/Ejercicio24_PanelVuelos.xml
<?xml version="1.0" encoding="UTF-8"?>
<aeropuerto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Ejercicio24_Prueba.xsd">
    <nombre>JFK</nombre>
    <vuelos>
        <vuelo código="V22" estado="R">
            <diario />
            <origen>New York</origen>
            <destino>Chicago</destino>
            <hora-salida>09:30:00</hora-salida>
            <hora-llegada>11:30:00</hora-llegada>
        </vuelo>
        <vuelo código="V23" estado="C">
            <origen>New York</origen>
            <destino>Miami</destino>
            <hora-salida>10:15:00</hora-salida>
            <hora-llegada>11:15:00</hora-llegada>
        </vuelo>
    </vuelos>
    <fecha>2013-12-20</fecha>
</aeropuerto>
