=== LauraRubioG/XSD_LenguajeDeMarca/AF2.5_EjerciciosVariosDeXSD_LauraRubioGallardo/Ejercicio11_InicialesReves.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="fichas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ficha" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="iniciales" type="inicialesNombre"/>
                            <xs:element name="edad" type="xs:integer"/>
                            <xs:element name="iniciales-al-reves" type="inicialesNombre"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- si lo ponemos aqui lo podemos usar para ambas -->
    <xs:simpleType name="inicialesNombre">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][A-Z][A-Z]"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

<!-- en caso de querer ponerlas en mayusculas ponemos  [a-zA-Z] -->

=== LauraRubioG/XSD_LenguajeDeMarca/AF2.5_EjerciciosVariosDeXSD_LauraRubioGallardo/Ejercicio11_InicialesReves.xml
<?xml version="1.0" encoding="UTF-8"?>
<fichas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Ejercicio11_InicialesReves.xsd">
    <ficha>
        <nombre>Ana Sanz Tin</nombre>
        <iniciales>AST</iniciales>
        <edad>22</edad>
        <iniciales-al-reves>TSA</iniciales-al-reves>
    </ficha>
    <ficha>
        <nombre>Iker Rubio Mol</nombre>
        <iniciales>IRM</iniciales>
        <edad>23</edad>
        <iniciales-al-reves>MRI</iniciales-al-reves>
    </ficha>
</fichas>
