=== LauraRubioG/XSD_LenguajeDeMarca/AF2.5_EjerciciosVariosDeXSD_LauraRubioGallardo/Ejercicio10_InicialesPersonasFamosas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="fichas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ficha" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="iniciales">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z][A-Z][A-Z]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="edad" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== LauraRubioG/XSD_LenguajeDeMarca/AF2.5_EjerciciosVariosDeXSD_LauraRubioGallardo/Ejercicio10_InicialesPersonasFamosas.xml
<?xml version="1.0" encoding="UTF-8"?>
<fichas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Ejercicio10_InicialesPersonasFamosas.xsd">
    <ficha>
        <nombre>Antonio Machado Ruiz</nombre>
        <iniciales>AMR</iniciales>
        <edad>22</edad>
    </ficha>
    <ficha>
        <nombre>Mario Moreno</nombre>
        <!-- añadimos una M mas ya que deben de ser tres no dos -->
        <iniciales>MMM</iniciales>
        <edad>23</edad>
    </ficha>
    <ficha>
        <!-- cambiamos el orden entre iniciales y nombre -->
        <nombre>Ada Lovelace</nombre>
        <iniciales>ALO</iniciales>
        <edad>24</edad>
    </ficha>
    <ficha>
        <nombre>pablo ruiz picasso</nombre>
        <!-- tiene que ser en mayusculas las iniciales -->
        <iniciales>PRP</iniciales>
        <edad>24</edad>
    </ficha>
</fichas>
